### ISSUE TITLE
Interrupt example code doesn't work on Pro Micro

### ISSUE THREAD

**Issue by chrise96** [sparkfun/LTC4150_Coulomb_Counter_BOB#2]
The issue is that the interrupt example takes a long time to show an interrupt message and gives me incorrect values of mA: 
Normal with polling example:
mAh: 1998.98 soc: 99.95% time: 367.73s mA: 1.67
mAh: 1998.81 soc: 99.94% time: 374.93s mA: 1.64
mAh: 1998.63 soc: 99.93% time: 363.59s mA: 1.69

With interrupt example (with same external microcontroller and external battery connected):
mAh: 1998.98 soc: 99.95% time: 1267.73s mA: 0.30 (something like this, dont have the log)
mAh: 1998.81 soc: 99.94% time: 1274.93s mA: 0.30 (something like this, dont have the log)

Polling example uses: if(interruptPin(INT==0){do something}

Interrupt uses attachInterrupt with an ISR on the INT pin. This is very similar to polling, so should give the same values.

Do you have any idea About this ?

Also, I don't get or see an interrupt message if I don't connect an external micro-controller to the "out" port of the LTC1450... Which I do get with the polling example.

**Comment by mgrusin** [comment]
Hi there, did you solve your issue? If you found the solution, it's good karma to post it here for us (and others) to see. Thanks!

**Comment by chrise96** [comment]
Hi Mike, 
I haven't figured this issue out yet. I'm happy you are still active! I cant make this one open but made some edits to the post. 

The issue is that the interrupt example takes a long time to show an interrupt message and gives me incorrect values of mA: 
Normal with polling:
mAh: 1998.98 soc: 99.95% time: 367.73s mA: 1.67
mAh: 1998.81 soc: 99.94% time: 374.93s mA: 1.64
mAh: 1998.63 soc: 99.93% time: 363.59s mA: 1.69

With interrupt example (with same external microcontroller and external battery connected):
mAh: 1998.98 soc: 99.95% time: 1267.73s mA: 0.30 (something like this, dont have the log)
mAh: 1998.81 soc: 99.94% time: 1274.93s mA: 0.30 (something like this, dont have the log)
