### ISSUE TITLE
multiple invalid libraries found

### ISSUE THREAD

**Issue by joebataz** [sparkfun/LTC4150_Coulomb_Counter_BOB#3]

**Comment by joebataz** [comment]
I am getting a long list of invalid library found in <path to arduino libraries> I  have just started up programming (or trying to) again after a couple of years. I am also getting
Documents/Arduino/libraries/FastLED/FastLED.h:12:2: warning: #warning FastLED version 3.001.000 (Not really a warning, just telling you here.) [-Wcpp]
 #warning FastLED version 3.001.000  (Not really a warning, just telling you here.)
I don't understand if this is an error or not. How do I get rid of these errors/warnings/whatever?

THANKS to whoever gets me this answer, I REALLY appreciate it!
joe b

**Comment by mgrusin** [comment]
If you haven't used it in a while, recent updates to Arduino may have rendered old libraries invalid. I would try opening sketch/include library/manage libraries, and see if any of them can be automatically updated. If they can't you may have to delete them and reinstall them manually. If you're stuck, our tech support department can help: https://www.sparkfun.com/technical_assistance. Hope this helps, good luck!

**Comment by joebataz** [comment]
Thanks Mike.
It resolved down to 5 problem libraries and one bad nano. Got new libraries where needed and fired up old reliable Mega and all is well now. Did a little refresher coding and looks like I actually remember how to code!

Thanks again!!

Joe B

**Comment by mgrusin** [comment]
That's GREAT to hear! Have fun and let us know if you have further questions (or want to show off what you're making! ;)
